### PR TITLE
Fix code based on the code review by Damien for Developer Release

### LINKED ISSUE #17: Fix code based on the code review by Damien for Developer Release
https://docs.google.com/document/d/1MtWiFyUpSkv2Vhy-WYdp7Mh57hqhHWtnbVYdgk8nBxc/edit?usp=sharing

*Actionable Items based on the google document above that are needed for the **developer release***

- [x] Create CRUD function for Range and modify other Entries to work with Range as an entry
- [x] rename ResourType to ResourceDef to align with HDK terminology
- [x] must_publish_dataset name should be changed to requires_validation. If it is true, DataSet must be committed to be retrievable in the validation The Objective Assesment must have the Data
- [x] update and delete shouldnt be allowed for dimension now. Updating dimension will be a problem for older assessments

### PR DESCRIPTION
**Pull request by tatssato**
Hey all, here are the changes that were introduced in this PR.

Note: This PR has plenty of type breaking changes. It will most likely break any codebase that uses the `@neighbourhoods/sensemaker-lite-types` if they use this latest version. Also, Im not that versed in publishing npm packages and I wouldn't want to break anything so I haven't published `0.5.0` as well.
If any of you can do it that would be really helpful 🙏 @weswalla @julioholon 

**Breaking Changes**
- [x] Create CRUD function for Range and modify other Entries to work with Range as an entry
  - `range_eh` field in `Dimension` is now an `EntryHash`.
  - There is a new `ConfigDimension` type
  - several type changes in `types` folder mainly in the config types (types that start with `Config...`)
- [x] rename ResourType to ResourceDef to align with HDK terminology
- [x] must_publish_dataset name should be changed to requires_validation. If it is true, DataSet must be committed to be retrievable in the validation The Objective Assesment must have the DataSet for this method
- [x] update and delete shouldnt be allowed for dimension now. Updating dimension will be a problem for older assessments 

**Additional Notes**
- Ranges are currently linked off of the path `ranges`. This can potentially cause DHT hotspot so it's worth revisitng in the [second cycle](https://github.com/orgs/neighbour-hoods/projects/1?pane=issue&itemId=21169064) of implementing Damien's review
- [ ] Since type definitions are also updated in the `types` folder, we have to bump the version of `@neighbourhoods/sensemaker-lite-types` in npm. I have bumped the version of it to `0.5.0` already.
-

### CODE REVIEW

**Comment by weswalla** [comment]
Just noting that because we merged #24 into this PR, merging this PR will close #24

File: dnas/sensemaker/zomes/coordinator/sensemaker/src/applet.rs [hunk 1]
```diff
@@ -87,18 +116,35 @@ pub fn create_entries_from_applet_config(
...
-        applet_config_typed_path(applet_config.name.clone())?.path_entry_hash()?,
+        applet_config_path.path_entry_hash()?,
         applet_config_eh.clone(),
         LinkTypes::AppletConfig,
         (),
     )?;
+    // for each resource type entry hash, create a link
+    resource_defs
+        .into_iter()
+        .map(|(_, resource_type_eh)| {
```
Comment (weswalla) [inline dnas/sensemaker/zomes/coordinator/sensemaker/src/applet.rs]: should we update `resource_type_eh` to `resource_def_eh` to stay consistent?

File: dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs [hunk 2]
```diff
@@ -35,37 +50,74 @@ pub fn get_assessments_for_resource(
...
-        maybe_input_dataset,
-    }: CreateAssessmentInput,
-) -> ExternResult<EntryHash> {
+pub fn create_assessment(CreateAssessmentInput { value, dimension_eh, resource_eh, resource_type_eh, maybe_input_dataset }: CreateAssessmentInput) -> ExternResult<EntryHash> {
     let assessment = Assessment {
         value,
         dimension_eh,
-        subject_eh,
+        resource_eh,
+        resource_type_eh,
```
Comment (weswalla) [inline dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs]: `resource_def_eh`

File: dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs [hunk 3]
```diff
@@ -35,37 +50,74 @@ pub fn get_assessments_for_resource(
 pub struct CreateAssessmentInput {
     pub value: RangeValue,
     pub dimension_eh: EntryHash,
-    pub subject_eh: EntryHash, // assuming this is the EH of the resource being assessed
+    pub resource_eh: EntryHash,
+    pub resource_type_eh: EntryHash,
```
Comment (weswalla) [inline dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs]: this should be renamed to `resource_def_eh`

File: dnas/sensemaker/zomes/coordinator/sensemaker/src/utils.rs [hunk 4]
```diff
@@ -54,3 +54,53 @@ pub fn flatten_btree_map<K, V: Clone>(btree_map: BTreeMap<K, Vec<V>>) -> Vec<V>
         .flatten()
         .collect::<Vec<V>>()
 }
+
+pub fn fetch_provider_resource(
+    resource_eh: EntryHash,
+    resource_type_eh: EntryHash,
```
Comment (weswalla) [inline dnas/sensemaker/zomes/coordinator/sensemaker/src/utils.rs]: `resource_def_eh`

**Review by weswalla — CHANGES_REQUESTED** [review]
I think the only thing left to do is a global search and replace of `resource_type_eh` (and any other forms like `ResourceTypeEh` if those exist as well) and replacing it with `resource_def_eh`

File: dnas/sensemaker/zomes/integrity/sensemaker/src/method.rs [hunk 5]
```diff
@@ -2,18 +2,18 @@ use std::collections::BTreeMap;
...
 #[hdk_entry_helper]
 #[derive(Clone)]
 pub struct Method {
     pub name: String,
-    pub target_resource_type_eh: EntryHash,
+    pub target_resource_def_eh: EntryHash,
     pub input_dimension_ehs: Vec<EntryHash>, // Validation: make sure it is subjective
     pub output_dimension_eh: EntryHash,      // Validation: make sure it is objective
     pub program: Program,                    // making enum for now, in design doc it is `AST`
     pub can_compute_live: bool,
```
Comment (julioholon) [inline dnas/sensemaker/zomes/integrity/sensemaker/src/method.rs:15]: I remember we wanted to rename this "can_compute_live" to something like "unrestricted_computation", meaning anyone can call this method (if False, only the CA can).

File: dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs [hunk 6]
```diff
@@ -35,37 +50,74 @@ pub fn get_assessments_for_resource(
...
+    let assessed_resources_typed_paths = base_path.children_paths()?;
+    let mut all_assessments: Vec<Vec<AssessmentWithDimensionAndResource>> = vec![];
+
+    // for each resource that has been assessed, crawl all children to get each dimension that it has been assessed along
+    for assessed_resource_path in assessed_resources_typed_paths {
+        let assessed_dimensions_for_resource_typed_paths = assessed_resource_path.children_paths()?;
+        
+        // for each dimension that a resource has been assessed, get the assessment
+        for assessed_dimension_path in assessed_dimensions_for_resource_typed_paths {
+            let assessments = get_links(assessed_dimension_path.path_entry_hash()?, LinkTypes::Assessment, None)?.into_iter().map(|link| {
```
Comment (julioholon) [inline dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs:94]: This `get_links` should be moved out of the for loop, no?

**Review by julioholon — APPROVED** [review]
Looks good to me.

For the future, we should resolve that get_links inside the for loop on `assessments.rs` coordinator zome.

Also, after integrating these changes, we need to review the applet_template and all other repos I guess.

File: dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs (hunk 6 above)
Comment (weswalla) [reply dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs:94]: Hey @julioholon, without further context I'm not sure why you are suggesting to move the `get_links` call outside of the for loop, could you further elaborate what you mean?

the reason I put the `get_links` inside the for loop is beause the path structure is like so `all_assessed_resources.{resource_eh_string}.{dimension_eh_string}`. (see https://github.com/neighbour-hoods/sensemaker-lite/blob/1c4d44de39786235785c37e3a79ccd29600b73e8/dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs#L143-L146), and then we create a link from this path to the `assessment_eh` when an assessment is created (see https://github.com/neighbour-hoods/sensemaker-lite/blob/1c4d44de39786235785c37e3a79ccd29600b73e8/dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs#L70-L78). 

Therefore, to get every assessment, we need to crawl every branch of this path. Meaning, for each `resource_eh` off the `all_assessed_resources.` base, we have to get every `dimension_eh`, and then for every `dimension_eh` get the links to each `assessment_eh`, hence the usage of `get_links` within the for loop https://github.com/neighbour-hoods/sensemaker-lite/blob/1c4d44de39786235785c37e3a79ccd29600b73e8/dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs#L94

**Comment by weswalla** [comment]
ok just replaced any remaining `resource_type` references/instances with `resource_def`. Tests pass locally, and once tests pass in github CI and we resolve @julioholon question about `get_links` I am comfortable to merge!

**Review by weswalla — APPROVED** [review]

File: dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs (hunk 6 above)
Comment (tatssato) [reply dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs:94]: @weswalla @julioholon I think what we can do here, (maybe in the future given this is not an urgent concern now), is to use holochain's parallel call (probably not the right name) in order to make the retrieval of these links faster. Something like https://github.com/holochain-open-dev/profiles/blob/main/crates/coordinator/src/lib.rs#L163-#L178 is what I am imagining we can do. This may not be the only improvement we can make but it certainly could make network calls like `get_links` return results faster than calling it sequentially.

**Comment by tatssato** [comment]
Thank you @weswalla for adding the final touches! I replied to the thread regarding `get_links`, if we are all okay to merge this PR for now, I will go ahead and do it :D

File: dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs (hunk 6 above)
Comment (julioholon) [reply dnas/sensemaker/zomes/coordinator/sensemaker/src/assessment.rs:94]: Yes, we can leave this for the future, as it's just a way to improve performance, and optimizing too early means releasing less often :)

**Comment by julioholon** [comment]
Yes, I think it's safe to merge too, thanks @tatssato !
